[package]
name = "bootstrap-node"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
futures = "0.3.25"
libp2p = { version = "0.51.3", features = ["tcp", "noise", "relay", "yamux", "tokio", "macros", "kad", "identify"] }
tokio = { version = "1.27.0", features = ["full"] }